### ISSUE TITLE
Why not add the click highlighted click during image capture

### ISSUE THREAD

**Issue by gr8tushar** [wrbl606/what-to-click#10]
Hi,
I was wondering, why didn't you add the click highlight while capturing the screenshot. This would be useful; in case one needs to save images to various locations (maybe cloud or even file system).
As of now, the images would only be saved without the click highlight.

**Comment by wrbl606** [comment]
There's no particular reason other than it's just easier to debug an html element. I have plans to include the click selection into the screenshot itself for eg. better Confluence compatibility.

**Comment by wrbl606** [comment]
Actually, an important reason is that the scrubs might not work as well if the text is obscured by the click position indicator
