### ISSUE TITLE
Change background color of screenshots

### ISSUE THREAD

**Issue by remy498** [wrbl606/what-to-click#3]
When a screenshot is partly off screen, a black background is added. Is it possible to change this color (ideally white)?

Thank you very much for your very useful extension.

**Comment by wrbl606** [comment]
I'm planning to overhaul the screenshot taking logic so there will be no option to have the out-of-bounds part in the image. I don't have any timeline for it though, so I'll keep you posted.

**Comment by wrbl606** [comment]
@remy498 Version 1.9.0 is not creating screenshots outside the document anymore, so the black bars shouldn't be an issue anymore. Please, let me know if this solved your problem!
