### ISSUE TITLE
FR: Track 'back'-action

### ISSUE THREAD

**Issue by djoris** [wrbl606/what-to-click#5]
In my workflows, I sometimes instruct people to go back to the previous page.
Currently it seems this action is ignored; in the recorded instructions, I just see the action added after going to the previous page.
as I see it, the action would either be 'go back to the previous page' or 'go (back) to [url]'. The latter would perhaps be more useful if the instruction asks to go back 2 pages in history.

**Comment by wrbl606** [comment]
Hello @djoris, thanks for your suggestion!

Since version 1.12.1 guides will have back navigation steps. Those won't work for backing up multiple times yet, so we can keep this issue open.

**Comment by wrbl606** [comment]
1.12.2 support multi-level back navigation steps 👍

**Comment by djoris** [comment]
Works exactly like I'd hoped. Thanks a bunch :)
