### ISSUE TITLE
Export as JSON

### ISSUE THREAD

**Issue by gr8tushar** [wrbl606/what-to-click#7]
Hi,
I was browsing through the code and found that you have created the code for exporting the document as JSON, but it is not available in the export menu.
Any specific reason for doing it?

Thanks,
Tushar

**Comment by wrbl606** [comment]
JSON export isn't fully ready yet. It only exports scrubbed images and step description, but is missing title, description, creation date, etc. It was prepared in an anticipation of the link feature, which from the survey responses isn't a top priority for users.

If you'll find it useful and have the ability to finish the future go for it, I'm happy to add another export option.
